# CREATE NETWORK BEFORE RUNNING DOCKER COMPOSE 
#docker network create "vehiclesfleet-logger-net"
version: '3.8'
services:
  loggermicroservice:
    image: loggermicroservice
    build:
      context: .
      dockerfile: LoggerMicroservice/Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - database
    networks:
      vehiclesfleet-logger-net:
        aliases:
          - logger
          
  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: mHDyhpoc4336HXuF0GYO
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1434
      MSSQL_DATABASE: VehiclesFleet
      MSSQL_PASSWORD: mHDyhpoc4336HXuF0GYO
    ports:
      - "1434:1434"
    networks:
      vehiclesfleet-logger-net:    
  
networks:
  vehiclesfleet-logger-net:
    external: true
